---
- name: Mount OCP empty Dir
  mount:
    path: /var/lib/origin/openshift.local.volumes
    src: /dev/mapper/ocpvg-emptydirlv
    state: unmounted
  tags: delete
#  when: cluster_host is defined

- name: Mount OCP ETCD Dir
  mount:
    path: /var/lib/etcd
    src: /dev/mapper/ocpvg-etcdlv
    state: unmounted
  tags: delete
#  when: master_host is defined

- name: Remove the logical volume.
  lvol:
    vg: ocpvg
    lv: emptydirlv
    state: absent
    force: yes
  tags: delete
#  when: cluster_host is defined

- name: Remove pvs 
  lvg:
    vg: ocpvg
    pvs: /dev/sdc1,/dev/sdd1
    state: absent
    force: true
  tags: delete
#  when: cluster_host is defined

- name: Remove the physical disk
  parted:
    device: /dev/sdc
    state: absent
    number: 1
  tags: delete

- name: Remove the logical volume.
  lvol:
    vg: ocpvg
    lv: etcdlv
    state: absent
    force: yes
  tags: delete
#  when: master_host is defined
#
- name: Remove pvs 
  lvg:
    vg: ocpvg
    pvs: /dev/sdc1,/dev/sdd1
    state: absent
    force: true
  tags: delete
#  when: cluster_host is defined

- name: Remove the physical disk
  parted:
    device: /dev/sdd
    state: absent
    number: 1
  tags: delete

- name: Restart LVM service
  service:
    name: lvm2-lvmetad
    state: restarted
  tags: delete
